version: "3.7"
services:
  sigepi-service:
    image: quarkus/backend-sigepi-jvm
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      VAR: examplevar
    depends_on:
      - sigepi-db

  sigepi-db:
    image: postgres:11.11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sigepidb
      - POSTGRES_USER=sigepidb
      - POSTGRES_PASSWORD=pass1234

