version: "3.7"
services:
  sigepi-service:
    image: quarkus/backend-sigepi-jvm
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - QUARKUS_LOG_LEVEL=INFO
      - QUARKUS_SWAGGER_UI_ALWAYS_INCLUDE=true
      - QUARKUS_DATASOURCE_USERNAME=sigepidb
      - QUARKUS_DATASOURCE_PASSWORD=pass1234
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://sigepi-db:5432/sigepidb
      - QUARKUS_DATASOURCE_JDBC_ACQUISITION_TIMEOUT=20000
      - QUARKUS_DATASOURCE_JDBC_INITIAL_SIZE=4
      - QUARKUS_DATASOURCE_JDBC_MIN_SIZE=4
      - QUARKUS_DATASOURCE_JDBC_MAX_SIZE=8
      - QUARKUS_DATASOURCE_JDBC_VALIDATION_QUERY_SQL=SELECT 1
      - QUARKUS_DATASOURCE_JDBC_MAX_LIFETIME=PT2H
      - PROPAGATED_HEADERS=Authorization,Accept-Language
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005" # Enable this for debug
    depends_on:
      - sigepi-db

  sigepi-db:
    image: postgres:11.11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sigepidb
      - POSTGRES_USER=sigepidb
      - POSTGRES_PASSWORD=pass1234

