FROM registry.access.redhat.com/ubi8/openjdk-11:1.11
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'

EXPOSE 8080
EXPOSE 5005

COPY --chown=185 target/backend-sigepi-0.1.0-SNAPSHOT-runner.jar /deployments/quarkus/backend-sigepi-0.1.0-SNAPSHOT-runner.jar


